"""check sync orm vs db

Revision ID: e183a07ca595
Revises: 7a0f90e24afe
Create Date: 2025-10-26 15:25:40.832661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e183a07ca595'
down_revision: Union[str, Sequence[str], None] = '7a0f90e24afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'search_tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=False)
    op.create_foreign_key(op.f('fk_employee_primary_org_unit_id_org_unit'), 'employee', 'org_unit', ['primary_org_unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_employee_manager_id_employee'), 'employee', 'employee', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_employee_manager_id_employee'), 'employee', type_='foreignkey')
    op.drop_constraint(op.f('fk_employee_primary_org_unit_id_org_unit'), 'employee', type_='foreignkey')
    op.alter_column('employee', 'search_tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=True)
    # ### end Alembic commands ###
