"""schema_probe

Revision ID: 0813816b6ca6
Revises: 25de9b4027a3
Create Date: 2025-11-01 13:58:38.415184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0813816b6ca6'
down_revision: Union[str, Sequence[str], None] = '25de9b4027a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_entity_snapshot', 'entity_type')
    op.drop_column('external_entity_snapshot', 'local_id')
    op.drop_constraint(op.f('fk_org_unit_last_applied_snapshot_id_external_entity_snapshot'), 'org_unit', type_='foreignkey')
    op.drop_column('org_unit', 'last_applied_snapshot_id')
    op.drop_column('sync_record', 'local_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_record', sa.Column('local_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('org_unit', sa.Column('last_applied_snapshot_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_org_unit_last_applied_snapshot_id_external_entity_snapshot'), 'org_unit', 'external_entity_snapshot', ['last_applied_snapshot_id'], ['id'], ondelete='SET NULL')
    op.add_column('external_entity_snapshot', sa.Column('local_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('external_entity_snapshot', sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
